name: Flutter Desktop Deployment

on:
  push:
    branches:
      - main

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          
      - name: Install project dependencies
        run: flutter pub get
        
      - name: Build artifacts
        run: flutter build windows --release
        
      - name: Package Release
        shell: pwsh
        run: |
          if (-Not (Test-Path -Path builds/windows)) {
            New-Item -Path builds/windows -ItemType Directory
          }
          Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath builds/windows/local_api_server-${{github.ref_name}}-windows.zip
        
      - name: Commit and push artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add builds/windows/local_api_server-${{github.ref_name}}-windows.zip
          git commit -m "Add Windows build artifacts for ${{ github.ref_name }}"
          git push origin build-artifacts
