name: Flutter Desktop Deployment

on:
  push:
    branches:
      - main

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Install project dependencies
        run: flutter pub get

      - name: Build artifacts
        run: flutter build windows --release

      - name: Package Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: local_api_server-${{ github.ref_name }}-windows.zip
          directory: build/windows/x64/runner/Release/

      - name: Configure Git
        run: |
          git config --global user.name 'ilhamwd'
          git config --global user.email 'iilhamwd@gmail.com'

      - name: Checkout build-artifacts branch
        run: |
          git fetch
          git checkout -B build-artifacts origin/build-artifacts || git checkout -B build-artifacts

      - name: Copy build artifacts
        run: |
          mkdir -p builds/windows
          cp build/windows/x64/runner/Release/local_api_server-main-windows.zip builds/windows/


      - name: Commit and push build artifacts
        run: |
          git add builds/windows/local_api_server-${{ github.ref_name }}-windows.zip
          git commit -m "Add Windows build artifacts for ${{ github.ref_name }}"
          git push origin build-artifacts --force
